In [35]:
import random

# Imports

import pandas as pd
import numpy as np
import random
import seaborn as sns
import matplotlib.pyplot as plt

sns.set()

In [3]:
# Importing gym and its other stuff
import gym
from gym import logger as gymlogger
gymlogger.set_level(40) # err only

env = gym.make("CartPole-v1")

In [95]:
### LOGGING OBJECT

class Logger:
    def __init__(self, filename='./data.csv'):
        self.filename = filename

    def __parseStats(self, stats) -> str:
        print(stats)
        obsv = stats[0]
        reward = stats[1]
        done = stats[2]
        info = stats[3]

        obsvCSV = ','.join([x.astype(str) for x in obsv])
        return f"{obsvCSV},{reward},{done},{info}"

    def log(self, stats, action, totalReward) -> None:
        # open file
        self.__parseStats(stats=stats)
        with open(self.filename, 'a') as file:
            file.write(f"{self.__parseStats(stats=stats)},{totalReward},{action}\n")
            pass


In [96]:
### Agent OBJECT

class Agent:
    def __init__(self, environment, logger:Logger) -> None:
        self.env = environment
        self.logger = logger
        self.isRunning = True
        self.curReward = 0

    def __reset(self):
        startState = self.env.reset()
        self.isRunning = True
        self.curReward = 0
        return startState

    def policy(self) -> int:
        return random.randint(0,1)

    def run(self) -> None:
        # self.logger.log(stats=self.__reset(), action=2)
        self.__reset()
        while self.isRunning:
            action = self.policy() # determining action
            stats = self.env.step(action) # execute action

            # update state
            self.isRunning = stats[2]==False
            self.curReward += stats[1]

            # log information etc
            self.logger.log(stats=stats, action=action, totalReward=self.curReward)


In [99]:
for _ in range(100):
    agt = Agent(gym.make("CartPole-v1"), Logger())
    agt.run()

(array([ 0.02615825,  0.19793059, -0.04914539, -0.31285596], dtype=float32), 1.0, False, False, {})
(array([ 0.02615825,  0.19793059, -0.04914539, -0.31285596], dtype=float32), 1.0, False, False, {})
(array([ 0.03011687,  0.39371696, -0.05540251, -0.6206238 ], dtype=float32), 1.0, False, False, {})
(array([ 0.03011687,  0.39371696, -0.05540251, -0.6206238 ], dtype=float32), 1.0, False, False, {})
(array([ 0.03799121,  0.58956707, -0.06781498, -0.9302283 ], dtype=float32), 1.0, False, False, {})
(array([ 0.03799121,  0.58956707, -0.06781498, -0.9302283 ], dtype=float32), 1.0, False, False, {})
(array([ 0.04978255,  0.39542276, -0.08641955, -0.6596035 ], dtype=float32), 1.0, False, False, {})
(array([ 0.04978255,  0.39542276, -0.08641955, -0.6596035 ], dtype=float32), 1.0, False, False, {})
(array([ 0.057691  ,  0.59163433, -0.09961162, -0.97819823], dtype=float32), 1.0, False, False, {})
(array([ 0.057691  ,  0.59163433, -0.09961162, -0.97819823], dtype=float32), 1.0, False, False, {})
